### ISSUE TITLE
panic: strconv.ParseInt: parsing "": invalid syntax

### ISSUE THREAD

**Issue by puzzlepeaches** [Static-Flow/goRecorder#1]
Hey there! I am super interested in using this project cross platform during engagements, but unfortunately don't know enough Go to fix the following issue. Please let me know if I need to provide any further information to help troubleshoot this issue.

Kernel and Operating System:
`Linux 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux
`

GO Version:
`go version go1.12.5 linux/amd64
`

Error Message:
```
panic: strconv.Atoi: parsing "": invalid syntax

goroutine 1 [running]:
main.splitScreens(0x0, 0x0, 0x0, 0x0, 0x0)
	/root/work/src/github.com/Static-Flow/goRecorder/recorder.go:26 +0x1e6
main.main()
	/root/work/src/github.com/Static-Flow/goRecorder/recorder.go:54 +0x20e

```

**Comment by Static-Flow** [comment]
Can you show me the command line you used? It looks like screedIds might be missing and I forgot to put any error checking or defaults if you forget to specify a screen.

**Comment by Static-Flow** [comment]
I pushed a change to check for supplying a valid set of screen Ids. Let me know if that fixes it.

**Comment by puzzlepeaches** [comment]
It seems to be working somewhat, but I am only able to see a screenshot taken slightly after F1 was pressed on the focused window. I really appreciate the quick fix!

![0_2019-06-03T09 10 20](https://user-images.githubusercontent.com/8538866/58808750-3d5a3000-85e0-11e9-8a0a-c4913429f31b.png)

I am using i3wm which may be making things more difficult than they need to be. Thanks again!

**Comment by Static-Flow** [comment]
There's a slight delay when compiling all the images especially if you are recording multiple screens at high resolutions but its a minute sliding window so you shouldn't miss any data in the pictures. That does bring up a good feature idea, variable resolutions to make the grabs quicker. Thanks for the bug report and happy hacking!
